socket-server:
  port: 9092
  host: 127.0.0.1

spring:
  application:
    name: relief
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/relief"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog/db.changelog-master.xml"
  data:
    redis:
      host: "localhost"
      port: 6379
      database: 1
      password: "root"
      username: "root"
